### ISSUE TITLE
Resource only working after restarting it.

### ISSUE THREAD

**Issue by Pop3310** [inferno-collection/Weapons#1]
I have been testing the resource for possible use in a community I am in. When first starting the server, the resource doesn't actually work. I only hear the click sound, but the fire mode doesn't change. After restarting the resource it started working.

**Comment by cm8263** [comment]
Do you have any errors in your console on either your client or your server?

Also, how are you starting the resource?

**Comment by Pop3310** [comment]
I don't believe so. I'll get a test server going with only that resource to see if it makes any difference.

I start it like this by simply putting "start inferno-weapons" into my server.cfg.

**Comment by cm8263** [comment]
> I don't believe so. I'll get a test server going with only that resource to see if it makes any difference.
> 
> I start it by simply putting "start inferno-weapons" into my server.cfg.

Alrighty, let me know how it goes.

**Comment by Pop3310** [comment]
So I have just tested the resource on a clean test server and it works fine. There seems to be something  interfering with it. Thanks for your help.

**Comment by cm8263** [comment]
> So I have just tested the resource on a clean test server and it works fine. There seems to be something interfering with it on the main server. Thanks for your help.

No worries. In the mean-time, try moving it to the very top or very bottom of the start list, see if that helps.

Let us know if you have any more issues.
