### ISSUE TITLE
Client Side - Limp Issue

### ISSUE THREAD

**Issue by Gregorsaur** [inferno-collection/Weapons#4]
When a person is injured, the limp animation will disappear after a very short amount of time (1/2 of a second) 

However on another persons screen the limp will remain for a realistic amount of time until they are back at a decent health level.

**Comment by cm8263** [comment]
Unable to reproduce. Could you provide some video of this occurring, as well as provide some server specs (including resources you're running) please?

**Comment by cm8263** [comment]
Still unable to repo in testing, can you provide any further details?

**Comment by cm8263** [comment]
Cannot repo and no further information provided.
