### ISSUE TITLE
New Suggestion/Edit

### ISSUE THREAD

**Issue by Gokaic** [inferno-collection/Weapons#6]
Sorry I'm not good with github and the like, but an addition I made on my end that adds the functionality to working in cars:

Remove the check for if in vehicle

Added to the FireMode.ShootingDisable loop:
--Disable shooting from vehicle
DisableControlAction(0, 92, true)

Added to Semi and burst:
--Right After DisablePlayerFiring(PlayerId(), true)
FireMode.ShootingDisable = true

This has worked for us and allows the guns to be semi auto even in vehicles

**Comment by cm8263** [comment]
Hey, thanks for your suggestion. Disabling the script while shooting out of vehicles was a deliberate action, so that people don't fumble with the safety while trying to do a drive-by haha.

I can write a little wiki page for this for people who would like that functionality. Thanks
