### ISSUE TITLE
[Suggestion] Controller Bindings

### ISSUE THREAD

**Issue by Mart475** [inferno-collection/Weapons#9]
Hey. It's me again, this script isn't great with a controller, and especially while trying to change fire modes using a controller. On an XBOX One controller it's set to the right thumbstick, and that could be changed to a better key, or disabled for controller. Thanks.

**Comment by cm8263** [comment]
Attempted to resolve in https://github.com/inferno-collection/Weapons/commit/782f5a37c4b28685d9dc4538b59c5bf9d3330582.

**Comment by cm8263** [comment]
Resolved in Public Beta Version 1.3.

https://github.com/inferno-collection/Weapons/releases/tag/v1.3-beta
